### ISSUE TITLE
Surfer render problem

### ISSUE THREAD

**Issue by luisfmcalado** [IMAGINARY/jsurf#3]
When I do a sum of x + x then doesn't render correctly anymore until restart the application.

![capturar](https://cloud.githubusercontent.com/assets/1489866/6168563/4ef14712-b2be-11e4-9b7a-cec56fb9efb8.PNG)

**Comment by porst17** [comment]
Interesting that no one found this bug before. I can confirm the weird behavior in SURFER. I have to check if it is directly related to SURFER or only to the rendering core (jsurf).

**Comment by luisfmcalado** [comment]
In the rendering core I at least loaded the file x+x and no exception was thrown so maybe is in the surfer side. I would like to help but can find the repo.

**Comment by porst17** [comment]
SURFER is not yet online due to special dependencies during code compilation (not runtime). I will look into it myself and report asap.

**Comment by porst17** [comment]
It seems like you found a bug in the internals of `jsurf`. The reason why you don't see an immediate problem with the rendering of `x+x=0` is that the rendering has to be repeated several times (this is what happens in `SURFER` in the render loop). The bug is probably related to some kind of internal optimization, but I am not sure yet.

By the way, it seems, like you can reproduce the bug with any surface by adding the `x+x` appropriately, e.g. for a surface defined by `f=0`, `x+x+f-2*x=0` will cause the rendering to fail, while `-2*x+f+x+x=0` will still produce the correct result.

I will need a few more hours to investigate this further and will report back.

**Comment by porst17** [comment]
The previous implementations of trivariate polynomial addition changed the values of its arguments sometimes. In most cases, nobody noticed since once you have the result of the addition the arguments were of no interest anymore. However, if the arguments was the polynomial `x` (represented internally as `1.0*x^1*y^0*z^0` and this should be constant during runtime), it was set to the result of the addition, i.e. in case of `x+x`to `2.0*x^1*y^0*z^0`. After a few iterations, you end up with pretty big coeffiecients for the internal representation of `x`. This also explains, why changing to another surface didn't solve the problem. The internal representation of `x` was flawed until program restart.

I will make a new SURFER release this week. Thanks a lot for your bug report. It seems like this issue already appeared several years ago. I had some complaints from exhibition visitors, but no one did ever provide me an example I could use to reproduce the behaviour!

**Comment by luisfmcalado** [comment]
I'm glad I could help.
